# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/meizu/m2note/setup-makefiles.sh

# copy whole folders
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/meizu/m2note/bin,system/bin)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/meizu/m2note/lib,system/lib)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/meizu/m2note/lib64,system/lib64)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/meizu/m2note/xbin,system/xbin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/meizu/m2note/usr,system/usr)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/meizu/m2note/vendor,system/vendor)

PRODUCT_COPY_FILES += \
    vendor/meizu/m2note/etc/bluetooth/auto_pair_blacklist.conf:system/etc/bluetooth/auto_pair_blacklist.conf \
    vendor/meizu/m2note/etc/bluetooth/auto_pair_devlist.conf:system/etc/bluetooth/auto_pair_devlist.conf \
    vendor/meizu/m2note/etc/bluetooth/iot_devlist.conf:system/etc/bluetooth/iot_devlist.conf \
    vendor/meizu/m2note/etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
    vendor/meizu/m2note/etc/bluetooth/ble_stack.conf:system/etc/bluetooth/ble_stack.conf \
    vendor/meizu/m2note/etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
    vendor/meizu/m2note/etc/bluetooth/bt_stack.conf.debug:system/etc/bluetooth/bt_stack.conf.debug \
    vendor/meizu/m2note/etc/bluetooth/bt_stack.conf.sqc:system/etc/bluetooth/bt_stack.conf.sqc \
    vendor/meizu/m2note/etc/bluetooth/btconfig.xml:system/etc/bluetooth/btconfig.xml \
    vendor/meizu/m2note/etc/custom.conf:system/etc/custom.conf \
    vendor/meizu/m2note/etc/perfservscntbl.txt:system/etc/perfservscntbl.txt \
    vendor/meizu/m2note/etc/firmware/catcher_filter_1_ltg_n.bin:system/etc/firmware/catcher_filter_1_ltg_n.bin \
    vendor/meizu/m2note/etc/firmware/catcher_filter_1_lwg_n.bin:system/etc/firmware/catcher_filter_1_lwg_n.bin \
    vendor/meizu/m2note/etc/firmware/dsp_1_ltg_n.bin:system/etc/firmware/dsp_1_ltg_n.bin \
    vendor/meizu/m2note/etc/firmware/dsp_1_lwg_n.bin:system/etc/firmware/dsp_1_lwg_n.bin \
    vendor/meizu/m2note/etc/firmware/modem_1_ltg_n.img:system/etc/firmware/modem_1_ltg_n.img \
    vendor/meizu/m2note/etc/firmware/modem_1_lwg_n.img:system/etc/firmware/modem_1_lwg_n.img \
    vendor/meizu/m2note/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin:system/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin \
    vendor/meizu/m2note/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin:system/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin \
    vendor/meizu/m2note/etc/firmware/WIFI_RAM_CODE_6735:system/etc/firmware/WIFI_RAM_CODE_6735 \
    vendor/meizu/m2note/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
    vendor/meizu/m2note/etc/mtklog-config.prop:system/etc/mtklog-config.prop \
    vendor/meizu/m2note/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/meizu/m2note/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/meizu/m2note/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/meizu/m2note/etc/.tp/thermal.conf:system/etc/.tp/thermal.conf \
    vendor/meizu/m2note/etc/.tp/thermal.high.conf:system/etc/.tp/thermal.high.conf \
    vendor/meizu/m2note/etc/.tp/thermal.mid.conf:system/etc/.tp/thermal.mid.conf \
    vendor/meizu/m2note/etc/.tp/thermal.low.conf:system/etc/.tp/thermal.low.conf \
    vendor/meizu/m2note/etc/.tp/thermal.off.conf:system/etc/.tp/thermal.off.conf \
